language: python
python:
  - "2.7"
env:
  - BLOG_CONFIG="$TRAVIS_BUILD_DIR/arecker/Blog/tests/testConfig.json"
install: "python setup.py install"
script:
  - "python setup.py nosetests"
  - "blog"
notifications:
  email: false